In [11]:
"""
WCOnline API Test Notebook
Simple test script to check WCOnline API responses
"""

import requests
import pandas as pd
import json
from datetime import datetime

API_KEY = "a519p8qKJGpnjo8asdgOIUNHLJ5342"
BASE_URL = "https://gannon.mywconline.com/api"

# ============================================================================
# CONFIGURATION
# ============================================================================
request_type = "CUSTOM"  # CUSTOM, AVAIL, APPTS, SCHED, STAFF
request_date = 20251205   # YYYYMMDD format (8 digits) - Change this date

# ============================================================================
# FETCH DATA
# ============================================================================
url = f"{BASE_URL}?type={request_type}&date={request_date}"
headers = {"Authorization": f"Bearer {API_KEY}"}

print(f"📡 Fetching {request_type} data for {request_date}")
print(f"🔗 URL: {url.replace(API_KEY, '***REDACTED***')}\n")

response = requests.get(url, headers=headers)
response_json = response.json()

print("RAW RESPONSE:")
print(json.dumps(response_json, indent=4))

# ============================================================================
# PROCESS DATA
# ============================================================================
df = None

if isinstance(response_json, list):
    df = pd.DataFrame(response_json)
    print(f"\n✅ Response is a LIST with {len(df)} items")
    print("\nFull DataFrame:")
    display(df)
elif isinstance(response_json, dict):
    for key, value in response_json.items():
        if isinstance(value, list):
            print(f"\n✅ Found list under key '{key}' with {len(value)} items")
            df = pd.DataFrame(value)
            display(df)
            break
    if df is None:
        print("\n⚠️ No list data found in response")
        print(f"Response keys: {list(response_json.keys())}")
else:
    print(f"\n⚠️ Unexpected format: {type(response_json)}")

# ============================================================================
# FILTER FOR STEM CENTER
# ============================================================================
if df is not None and "Schedule Title" in df.columns:
    stem_df = df[df["Schedule Title"].str.upper().str.contains("STEM CENTER", na=False)]
    
    print("\n" + "="*70)
    print("⭐ STEM CENTER FILTERED RESULTS ⭐")
    print("="*70)
    print(f"Found {len(stem_df)} STEM Center entries out of {len(df)} total")
    
    if len(stem_df) > 0:
        display(stem_df)
    else:
        print("No STEM Center entries found")
else:
    print("\n⚠️ Cannot filter — DataFrame empty or missing 'Schedule Title' column.")
    if df is not None:
        print(f"Available columns: {list(df.columns)}")

📡 Fetching CUSTOM data for 20251205
🔗 URL: https://gannon.mywconline.com/api?type=CUSTOM&date=20251205

RAW RESPONSE:
[
    {
        "Schedule Title": "OAS - Office of Accessibility Services",
        "Staff or Resource": "Testing room 1018",
        "Start Time": "9:00 am",
        "End Time": "10:45 am"
    },
    {
        "Schedule Title": "OAS - Office of Accessibility Services",
        "Staff or Resource": "Testing room 1016",
        "Start Time": "12:30 pm",
        "End Time": "2:30 pm"
    },
    {
        "Schedule Title": "OAS - Office of Accessibility Services",
        "Staff or Resource": "Testing Room G",
        "Start Time": "9:00 am",
        "End Time": "11:00 am"
    },
    {
        "Schedule Title": "OAS - Office of Accessibility Services",
        "Staff or Resource": "Testing room 1018",
        "Start Time": "11:15 am",
        "End Time": "12:00 pm"
    },
    {
        "Schedule Title": "OAS - Office of Accessibility Services",
        "Staff or Resource": "Testing Room A",
        "Start Time": "11:15 am",
        "End Time": "12:30 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Kara B.",
        "Start Time": "2:00 pm",
        "End Time": "3:00 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Jonathan H.",
        "Start Time": "2:00 pm",
        "End Time": "3:00 pm"
    },
    {
        "Schedule Title": "OAS - Office of Accessibility Services",
        "Staff or Resource": "Testing Room B",
        "Start Time": "12:30 pm",
        "End Time": "2:00 pm"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Sophia M.",
        "Start Time": "12:00 pm",
        "End Time": "12:30 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Prashriti A.",
        "Start Time": "2:00 pm",
        "End Time": "3:00 pm"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Kae C.",
        "Start Time": "2:00 pm",
        "End Time": "2:30 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Prashriti A.",
        "Start Time": "4:00 pm",
        "End Time": "5:00 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Isaac W.",
        "Start Time": "3:00 pm",
        "End Time": "4:00 pm"
    },
    {
        "Schedule Title": "Graduate Writing FA25",
        "Staff or Resource": "Salina G. ",
        "Start Time": "8:00 pm",
        "End Time": "9:00 pm"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Alina S.",
        "Start Time": "1:00 pm",
        "End Time": "1:30 pm"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Allyson M.",
        "Start Time": "3:00 pm",
        "End Time": "4:00 pm"
    },
    {
        "Schedule Title": "Graduate Writing FA25",
        "Staff or Resource": "Salina G. ",
        "Start Time": "6:00 pm",
        "End Time": "7:00 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Avish M.",
        "Start Time": "4:00 pm",
        "End Time": "5:00 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Avish M.",
        "Start Time": "3:00 pm",
        "End Time": "4:00 pm"
    },
    {
        "Schedule Title": "OAS - Office of Accessibility Services",
        "Staff or Resource": "Testing Room D",
        "Start Time": "1:00 pm",
        "End Time": "3:00 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Hoang T.",
        "Start Time": "5:00 pm",
        "End Time": "6:00 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Quoc N.",
        "Start Time": "5:00 pm",
        "End Time": "6:00 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Quoc N.",
        "Start Time": "6:00 pm",
        "End Time": "7:00 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Hannah P.",
        "Start Time": "3:00 pm",
        "End Time": "4:00 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Izzy G.",
        "Start Time": "3:00 pm",
        "End Time": "4:00 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Izzy G.",
        "Start Time": "4:00 pm",
        "End Time": "5:00 pm"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Harry J. ",
        "Start Time": "11:30 am",
        "End Time": "12:30 pm"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Isaac W.",
        "Start Time": "4:00 pm",
        "End Time": "5:00 pm"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Allyson M.",
        "Start Time": "2:00 pm",
        "End Time": "2:30 pm"
    },
    {
        "Schedule Title": "Graduate Writing FA25",
        "Staff or Resource": "Allyson M.",
        "Start Time": "6:00 pm",
        "End Time": "9:00 pm"
    }
]

✅ Response is a LIST with 30 items

Full DataFrame:

,Schedule Title,Staff or Resource,Start Time,End Time
0,OAS - Office of Accessibility Services,Testing room 1018,9:00 am,10:45 am
1,OAS - Office of Accessibility Services,Testing room 1016,12:30 pm,2:30 pm
2,OAS - Office of Accessibility Services,Testing Room G,9:00 am,11:00 am
3,OAS - Office of Accessibility Services,Testing room 1018,11:15 am,12:00 pm
4,OAS - Office of Accessibility Services,Testing Room A,11:15 am,12:30 pm
5,STEM Center,Kara B.,2:00 pm,3:00 pm
6,STEM Center,Jonathan H.,2:00 pm,3:00 pm
7,OAS - Office of Accessibility Services,Testing Room B,12:30 pm,2:00 pm
8,Writing Center/Humanities Tutoring FA25,Sophia M.,12:00 pm,12:30 pm
9,STEM Center,Prashriti A.,2:00 pm,3:00 pm
10,Writing Center/Humanities Tutoring FA25,Kae C.,2:00 pm,2:30 pm
11,STEM Center,Prashriti A.,4:00 pm,5:00 pm
12,STEM Center,Isaac W.,3:00 pm,4:00 pm
13,Graduate Writing FA25,Salina G.,8:00 pm,9:00 pm
14,Writing Center/Humanities Tutoring FA25,Alina S.,1:00 pm,1:30 pm
15,Writing Center/Humanities Tutoring FA25,Allyson M.,3:00 pm,4:00 pm
16,Graduate Writing FA25,Salina G.,6:00 pm,7:00 pm
17,STEM Center,Avish M.,4:00 pm,5:00 pm
18,STEM Center,Avish M.,3:00 pm,4:00 pm
19,OAS - Office of Accessibility Services,Testing Room D,1:00 pm,3:00 pm
20,STEM Center,Hoang T.,5:00 pm,6:00 pm
21,STEM Center,Quoc N.,5:00 pm,6:00 pm
22,STEM Center,Quoc N.,6:00 pm,7:00 pm
23,STEM Center,Hannah P.,3:00 pm,4:00 pm
24,STEM Center,Izzy G.,3:00 pm,4:00 pm
25,STEM Center,Izzy G.,4:00 pm,5:00 pm
26,Writing Center/Humanities Tutoring FA25,Harry J.,11:30 am,12:30 pm
27,STEM Center,Isaac W.,4:00 pm,5:00 pm
28,Writing Center/Humanities Tutoring FA25,Allyson M.,2:00 pm,2:30 pm
29,Graduate Writing FA25,Allyson M.,6:00 pm,9:00 pm

======================================================================
⭐ STEM CENTER FILTERED RESULTS ⭐
======================================================================
Found 14 STEM Center entries out of 30 total

   Schedule Title Staff or Resource Start Time End Time
5     STEM Center           Kara B.    2:00 pm  3:00 pm
6     STEM Center       Jonathan H.    2:00 pm  3:00 pm
9     STEM Center      Prashriti A.    2:00 pm  3:00 pm
11    STEM Center      Prashriti A.    4:00 pm  5:00 pm
12    STEM Center          Isaac W.    3:00 pm  4:00 pm
17    STEM Center          Avish M.    4:00 pm  5:00 pm
18    STEM Center          Avish M.    3:00 pm  4:00 pm
20    STEM Center          Hoang T.    5:00 pm  6:00 pm
21    STEM Center           Quoc N.    5:00 pm  6:00 pm
22    STEM Center           Quoc N.    6:00 pm  7:00 pm
23    STEM Center         Hannah P.    3:00 pm  4:00 pm
24    STEM Center           Izzy G.    3:00 pm  4:00 pm
25    STEM Center           Izzy G.    4:00 pm  5:00 pm
27    STEM Center          Isaac W.    4:00 pm  5:00 pm