In [16]:
"""
WCOnline API Test Notebook
Simple test script to check WCOnline API responses
"""

import requests
import pandas as pd
import json
from datetime import datetime

API_KEY = "a519p8qKJGpnjo8asdgOIUNHLJ5342"
BASE_URL = "https://gannon.mywconline.com/api"

# ============================================================================
# CONFIGURATION
# ============================================================================
request_type = "CUSTOM"  # CUSTOM, AVAIL, APPTS, SCHED, STAFF
request_date = 20250902   # YYYYMMDD format (8 digits) - Change this date

# ============================================================================
# FETCH DATA
# ============================================================================
url = f"{BASE_URL}?type={request_type}&date={request_date}"
headers = {"Authorization": f"Bearer {API_KEY}"}

print(f"📡 Fetching {request_type} data for {request_date}")
print(f"🔗 URL: {url.replace(API_KEY, '***REDACTED***')}\n")

response = requests.get(url, headers=headers)
response_json = response.json()

print("RAW RESPONSE:")
print(json.dumps(response_json, indent=4))

# ============================================================================
# PROCESS DATA
# ============================================================================
df = None

if isinstance(response_json, list):
    df = pd.DataFrame(response_json)
    print(f"\n✅ Response is a LIST with {len(df)} items")
    print("\nFull DataFrame:")
    display(df)
elif isinstance(response_json, dict):
    for key, value in response_json.items():
        if isinstance(value, list):
            print(f"\n✅ Found list under key '{key}' with {len(value)} items")
            df = pd.DataFrame(value)
            display(df)
            break
    if df is None:
        print("\n⚠️ No list data found in response")
        print(f"Response keys: {list(response_json.keys())}")
else:
    print(f"\n⚠️ Unexpected format: {type(response_json)}")

# ============================================================================
# FILTER FOR STEM CENTER
# ============================================================================
if df is not None and "Schedule Title" in df.columns:
    stem_df = df[df["Schedule Title"].str.upper().str.contains("STEM CENTER", na=False)]
    
    print("\n" + "="*70)
    print("⭐ STEM CENTER FILTERED RESULTS ⭐")
    print("="*70)
    print(f"Found {len(stem_df)} STEM Center entries out of {len(df)} total")
    
    if len(stem_df) > 0:
        display(stem_df)
    else:
        print("No STEM Center entries found")
else:
    print("\n⚠️ Cannot filter — DataFrame empty or missing 'Schedule Title' column.")
    if df is not None:
        print(f"Available columns: {list(df.columns)}")

📡 Fetching CUSTOM data for 20250902
🔗 URL: https://gannon.mywconline.com/api?type=CUSTOM&date=20250902

RAW RESPONSE:
[
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "2:00 pm",
        "End Time": "2:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-27 9:15:22 am",
        "Created By": "Clay, Carter",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Prier"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "3:00 pm",
        "End Time": "3:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-27 9:16:23 am",
        "Created By": "Clay, Carter",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Prier"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "2:30 pm",
        "End Time": "3:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-27 9:17:18 am",
        "Created By": "Clay, Carter",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Prier"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "3:30 pm",
        "End Time": "4:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-27 9:18:02 am",
        "Created By": "Clay, Carter",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Prier"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "4:00 pm",
        "End Time": "4:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-27 9:18:55 am",
        "Created By": "Clay, Carter",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Prier"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "4:30 pm",
        "End Time": "5:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-27 9:20:32 am",
        "Created By": "Clay, Carter",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Prier"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Lexa Y.",
        "Appointment Date": "2025-09-02",
        "Start Time": "2:00 pm",
        "End Time": "3:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "CHEM105 Physiological Chem - Dr Aaron Forbes",
        "Created": "2025-08-28 6:26:49 pm",
        "Created By": "Dunn, Chloe ",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Aaron Forbes "
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Quoc N.",
        "Appointment Date": "2025-09-02",
        "Start Time": "5:00 pm",
        "End Time": "6:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "BCOR111 Prin Microecomonics - Dr M Roth",
        "Created": "2025-08-28 7:28:03 pm",
        "Created By": "Tejwani, Drishti",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Roth"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Kae C.",
        "Appointment Date": "2025-09-02",
        "Start Time": "12:30 pm",
        "End Time": "1:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "",
        "Created": "2025-08-29 7:52:59 am",
        "Created By": "Stainsby, Jaye",
        "Repeating": "",
        "Course": "SCWK_221 (Hum Behavr/Soc Env 1)",
        "Course instructor": "Dr. Lichtenwalter"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Maeve M. ",
        "Appointment Date": "2025-09-02",
        "Start Time": "1:00 pm",
        "End Time": "1:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "",
        "Created": "2025-08-29 8:24:25 am",
        "Created By": "Fallon, Olivia",
        "Repeating": "",
        "Course": "SCWK_221 (Hum Behavr/Soc Env 1)",
        "Course instructor": "Dr. Litchenwalter"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Maeve M. ",
        "Appointment Date": "2025-09-02",
        "Start Time": "12:00 pm",
        "End Time": "12:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "",
        "Created": "2025-08-29 9:29:40 am",
        "Created By": "Thompson, Kayla",
        "Repeating": "",
        "Course": "CHEM_368 (Biochemical Pathways)",
        "Course instructor": "Dr. Betty Jo Chitester"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Kara B.",
        "Appointment Date": "2025-09-02",
        "Start Time": "2:00 pm",
        "End Time": "3:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "CHEM103 Chemistry of Life 1 - Dr Betty Jo Chitester",
        "Created": "2025-08-29 9:48:00 am",
        "Created By": "Liberati, Nick",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Chitester"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "5:00 pm",
        "End Time": "5:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-29 10:02:28 am",
        "Created By": "Sebastian, Nora",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Michael Caulfield"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "6:30 pm",
        "End Time": "7:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-29 11:19:11 am",
        "Created By": "Gankhuyag, Altangerel",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Michael Caulfield"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Matthew T.",
        "Appointment Date": "2025-09-02",
        "Start Time": "7:00 pm",
        "End Time": "8:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "CHEM114 General Chemistry 2 - any instructors",
        "Created": "2025-08-29 11:24:14 am",
        "Created By": "Bikeet, Carol Amir Boshra Abdo",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr.Tallmadge"
    },
    {
        "Schedule Title": "Graduate Writing FA25",
        "Staff or Resource": "Hannah N.",
        "Appointment Date": "2025-09-02",
        "Start Time": "8:00 pm",
        "End Time": "9:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "ETUTORING",
        "Focus": "",
        "Created": "2025-08-30 12:07:40 pm",
        "Created By": "Clark, Eric",
        "Repeating": "",
        "Course": "DNURS_806 (Health Care Informatics)",
        "Course instructor": "Dr. Patricia Hemshrodt"
    },
    {
        "Schedule Title": "OAS - Office of Accessibility Services",
        "Staff or Resource": "Testing Room E",
        "Appointment Date": "2025-09-02",
        "Start Time": "12:00 pm",
        "End Time": "12:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-30 1:06:50 pm",
        "Created By": "Elnour, Mariam",
        "Repeating": "",
        "Course": "BIOL_368 (Human Physiology)",
        "Course instructor": "Mary Vagula"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "5:30 pm",
        "End Time": "6:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-31 5:56:34 pm",
        "Created By": "Orte Blanch, Claudia",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Prier"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "6:00 pm",
        "End Time": "6:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-08-31 5:57:09 pm",
        "Created By": "Orte Blanch, Claudia",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Prier"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Maeve M. ",
        "Appointment Date": "2025-09-02",
        "Start Time": "7:30 pm",
        "End Time": "8:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "",
        "Created": "2025-09-01 1:10:52 pm",
        "Created By": "Biles, Miranda ",
        "Repeating": "",
        "Course": "ENGL_101 (Foundations of Acad Writing)",
        "Course instructor": "Dr. Kaustav Mukherjee"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Matthew T.",
        "Appointment Date": "2025-09-02",
        "Start Time": "5:00 pm",
        "End Time": "6:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "ONLINE",
        "Focus": "SPRT391 Physio Exrc Sprt Lab - Ms Kara Kern",
        "Created": "2025-09-01 6:22:32 pm",
        "Created By": "Cernuto, Olivia",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Kara Kern"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "6:00 pm",
        "End Time": "6:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-01 7:38:41 pm",
        "Created By": "Garrido Lecca Zagaceta, Bastiaan",
        "Repeating": "",
        "Course": "",
        "Course instructor": "David Prier"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "7:30 pm",
        "End Time": "8:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-01 7:39:32 pm",
        "Created By": "Garrido Lecca Zagaceta, Bastiaan",
        "Repeating": "",
        "Course": "",
        "Course instructor": "David Prier"
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Kae C.",
        "Appointment Date": "2025-09-02",
        "Start Time": "11:00 am",
        "End Time": "11:30 am",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "",
        "Created": "2025-09-01 8:00:24 pm",
        "Created By": "Basnet, Bhumika",
        "Repeating": "",
        "Course": "ENGL_101 (Foundations of Acad Writing)",
        "Course instructor": "Kaustav Mukherjee"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "5:00 pm",
        "End Time": "5:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 12:04:04 am",
        "Created By": "Wasielewski, Maja ",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Prier"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "3:00 pm",
        "End Time": "3:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 6:32:39 am",
        "Created By": "Dhakal, Sambriddhi ",
        "Repeating": "",
        "Course": "",
        "Course instructor": "David Prier "
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "3:30 pm",
        "End Time": "4:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 6:33:15 am",
        "Created By": "Dhakal, Sambriddhi ",
        "Repeating": "",
        "Course": "",
        "Course instructor": "David Prier "
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "2:30 pm",
        "End Time": "3:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 6:34:05 am",
        "Created By": "Dhakal, Sambriddhi ",
        "Repeating": "",
        "Course": "",
        "Course instructor": "David Prier "
    },
    {
        "Schedule Title": " Writing Center/Humanities Tutoring FA25",
        "Staff or Resource": "Maeve M. ",
        "Appointment Date": "2025-09-02",
        "Start Time": "11:00 am",
        "End Time": "11:30 am",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "",
        "Created": "2025-09-02 8:30:08 am",
        "Created By": "Hargate, Angelina",
        "Repeating": "",
        "Course": "BME_356 (Motion Capture Lab)",
        "Course instructor": "Ji"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "5:00 pm",
        "End Time": "5:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 8:43:45 am",
        "Created By": "Wright, Erin",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Michael J Caulfield "
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "5:30 pm",
        "End Time": "6:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 8:46:57 am",
        "Created By": "Wright, Erin",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Michael J Caulfield "
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "6:00 pm",
        "End Time": "6:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 8:54:26 am",
        "Created By": "Wright, Erin",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Michael J Caulfield "
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "2:00 pm",
        "End Time": "2:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 9:13:13 am",
        "Created By": "Le, Tue",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Michael Caufield"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "7:00 pm",
        "End Time": "7:30 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 9:17:45 am",
        "Created By": "Vizcaino, Tommi",
        "Repeating": "",
        "Course": "",
        "Course instructor": "David Prier"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "4:30 pm",
        "End Time": "5:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 9:33:01 am",
        "Created By": "Norman, Sadie",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Prier"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Cloe M. ",
        "Appointment Date": "2025-09-02",
        "Start Time": "2:00 pm",
        "End Time": "3:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "ME201 Statics - any instructors",
        "Created": "2025-09-02 10:06:09 am",
        "Created By": "Mateo Villaronga, Cloe",
        "Repeating": "",
        "Course": "",
        "Course instructor": "steinbrink"
    },
    {
        "Schedule Title": "STEM Center Proctored Exams",
        "Staff or Resource": "Calculus Readiness Exam",
        "Appointment Date": "2025-09-02",
        "Start Time": "7:30 pm",
        "End Time": "8:00 pm",
        "Walk-In/Drop-In": "",
        "Missed/No-Show": "",
        "Online": "",
        "Focus": "",
        "Created": "2025-09-02 12:58:12 pm",
        "Created By": "Baktybekov, Tamirlan",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Michael Caulfield"
    },
    {
        "Schedule Title": "STEM Center",
        "Staff or Resource": "Clara B.",
        "Appointment Date": "2025-09-02",
        "Start Time": "4:00 pm",
        "End Time": "5:00 pm",
        "Walk-In/Drop-In": "YES",
        "Missed/No-Show": "",
        "Online": "0",
        "Focus": "MATH140 Calculus 1 - any instructors",
        "Created": "2025-09-02 3:01:29 pm",
        "Created By": "Bourke Hurtado, Clara",
        "Repeating": "",
        "Course": "",
        "Course instructor": "Dr. Prier"

,Schedule Title,Staff or Resource,Appointment Date,Start Time,End Time,Walk-In/Drop-In,Missed/No-Show,Online,Focus,Created,Created By,Repeating,Course,Course instructor
0,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,2:00 pm,2:30 pm,,,,,2025-08-27 9:15:22 am,"Clay, Carter",,,Dr. Prier
1,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,3:00 pm,3:30 pm,,,,,2025-08-27 9:16:23 am,"Clay, Carter",,,Dr. Prier
2,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,2:30 pm,3:00 pm,,,,,2025-08-27 9:17:18 am,"Clay, Carter",,,Dr. Prier
3,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,3:30 pm,4:00 pm,,,,,2025-08-27 9:18:02 am,"Clay, Carter",,,Dr. Prier
4,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,4:00 pm,4:30 pm,,,,,2025-08-27 9:18:55 am,"Clay, Carter",,,Dr. Prier
5,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,4:30 pm,5:00 pm,,,,,2025-08-27 9:20:32 am,"Clay, Carter",,,Dr. Prier
6,STEM Center,Lexa Y.,2025-09-02,2:00 pm,3:00 pm,,,0,CHEM105 Physiological Chem - Dr Aaron Forbes,2025-08-28 6:26:49 pm,"Dunn, Chloe",,,Dr. Aaron Forbes
7,STEM Center,Quoc N.,2025-09-02,5:00 pm,6:00 pm,,,0,BCOR111 Prin Microecomonics - Dr M Roth,2025-08-28 7:28:03 pm,"Tejwani, Drishti",,,Roth
8,Writing Center/Humanities Tutoring FA25,Kae C.,2025-09-02,12:30 pm,1:00 pm,,,0,,2025-08-29 7:52:59 am,"Stainsby, Jaye",,SCWK_221 (Hum Behavr/Soc Env 1),Dr. Lichtenwalter
9,Writing Center/Humanities Tutoring FA25,Maeve M.,2025-09-02,1:00 pm,1:30 pm,,,0,,2025-08-29 8:24:25 am,"Fallon, Olivia",,SCWK_221 (Hum Behavr/Soc Env 1),Dr. Litchenwalter
10,Writing Center/Humanities Tutoring FA25,Maeve M.,2025-09-02,12:00 pm,12:30 pm,,,0,,2025-08-29 9:29:40 am,"Thompson, Kayla",,CHEM_368 (Biochemical Pathways),Dr. Betty Jo Chitester
11,STEM Center,Kara B.,2025-09-02,2:00 pm,3:00 pm,,,0,CHEM103 Chemistry of Life 1 - Dr Betty Jo Chit...,2025-08-29 9:48:00 am,"Liberati, Nick",,,Chitester
12,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,5:00 pm,5:30 pm,,,,,2025-08-29 10:02:28 am,"Sebastian, Nora",,,Michael Caulfield
13,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,6:30 pm,7:00 pm,,,,,2025-08-29 11:19:11 am,"Gankhuyag, Altangerel",,,Michael Caulfield
14,STEM Center,Matthew T.,2025-09-02,7:00 pm,8:00 pm,,,0,CHEM114 General Chemistry 2 - any instructors,2025-08-29 11:24:14 am,"Bikeet, Carol Amir Boshra Abdo",,,Dr.Tallmadge
15,Graduate Writing FA25,Hannah N.,2025-09-02,8:00 pm,9:00 pm,,,ETUTORING,,2025-08-30 12:07:40 pm,"Clark, Eric",,DNURS_806 (Health Care Informatics),Dr. Patricia Hemshrodt
16,OAS - Office of Accessibility Services,Testing Room E,2025-09-02,12:00 pm,12:30 pm,,,,,2025-08-30 1:06:50 pm,"Elnour, Mariam",,BIOL_368 (Human Physiology),Mary Vagula
17,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,5:30 pm,6:00 pm,,,,,2025-08-31 5:56:34 pm,"Orte Blanch, Claudia",,,Dr. Prier
18,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,6:00 pm,6:30 pm,,,,,2025-08-31 5:57:09 pm,"Orte Blanch, Claudia",,,Dr. Prier
19,Writing Center/Humanities Tutoring FA25,Maeve M.,2025-09-02,7:30 pm,8:00 pm,,,0,,2025-09-01 1:10:52 pm,"Biles, Miranda",,ENGL_101 (Foundations of Acad Writing),Dr. Kaustav Mukherjee
20,STEM Center,Matthew T.,2025-09-02,5:00 pm,6:00 pm,,,ONLINE,SPRT391 Physio Exrc Sprt Lab - Ms Kara Kern,2025-09-01 6:22:32 pm,"Cernuto, Olivia",,,Dr. Kara Kern
21,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,6:00 pm,6:30 pm,,,,,2025-09-01 7:38:41 pm,"Garrido Lecca Zagaceta, Bastiaan",,,David Prier
22,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,7:30 pm,8:00 pm,,,,,2025-09-01 7:39:32 pm,"Garrido Lecca Zagaceta, Bastiaan",,,David Prier
23,Writing Center/Humanities Tutoring FA25,Kae C.,2025-09-02,11:00 am,11:30 am,,,0,,2025-09-01 8:00:24 pm,"Basnet, Bhumika",,ENGL_101 (Foundations of Acad Writing),Kaustav Mukherjee
24,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,5:00 pm,5:30 pm,,,,,2025-09-02 12:04:04 am,"Wasielewski, Maja",,,Dr. Prier
25,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,3:00 pm,3:30 pm,,,,,2025-09-02 6:32:39 am,"Dhakal, Sambriddhi",,,David Prier
26,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,3:30 pm,4:00 pm,,,,,2025-09-02 6:33:15 am,"Dhakal, Sambriddhi",,,David Prier
27,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,2:30 pm,3:00 pm,,,,,2025-09-02 6:34:05 am,"Dhakal, Sambriddhi",,,David Prier
28,Writing Center/Humanities Tutoring FA25,Maeve M.,2025-09-02,11:00 am,11:30 am,,,0,,2025-09-02 8:30:08 am,"Hargate, Angelina",,BME_356 (Motion Capture Lab),Ji
29,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,5:00 pm,5:30 pm,,,,,2025-09-02 8:43:45 am,"Wright, Erin",,,Michael J Caulfield
30,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,5:30 pm,6:00 pm,,,,,2025-09-02 8:46:57 am,"Wright, Erin",,,Michael J Caulfield
31,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,6:00 pm,6:30 pm,,,,,2025-09-02 8:54:26 am,"Wright, Erin",,,Michael J Caulfield
32,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,2:00 pm,2:30 pm,,,,,2025-09-02 9:13:13 am,"Le, Tue",,,Michael Caufield
33,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,7:00 pm,7:30 pm,,,,,2025-09-02 9:17:45 am,"Vizcaino, Tommi",,,David Prier
34,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,4:30 pm,5:00 pm,,,,,2025-09-02 9:33:01 am,"Norman, Sadie",,,Prier
35,STEM Center,Cloe M.,2025-09-02,2:00 pm,3:00 pm,,,0,ME201 Statics - any instructors,2025-09-02 10:06:09 am,"Mateo Villaronga, Cloe",,,steinbrink
36,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,7:30 pm,8:00 pm,,,,,2025-09-02 12:58:12 pm,"Baktybekov, Tamirlan",,,Michael Caulfield
37,STEM Center,Clara B.,2025-09-02,4:00 pm,5:00 pm,YES,,0,MATH140 Calculus 1 - any instructors,2025-09-02 3:01:29 pm,"Bourke Hurtado, Clara",,,Dr. Prier
38,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,6:30 pm,7:00 pm,,,,,2025-09-02 3:36:14 pm,"Baktybekov, Tamirlan",,,Michael Caulfield
39,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,7:00 pm,7:30 pm,,,,,2025-09-02 3:41:57 pm,"Baktybekov, Tamirlan",,,Michael Caulfield
40,STEM Center,Khanh L.,2025-09-02,7:00 pm,8:00 pm,,,0,BIOL115 Hum Anatomy Phys 1 - Mrs Renee Foradori,2025-09-02 4:31:03 pm,"Tran, Nguyen Thuc",,,foradori
41,Graduate Writing FA25,Hannah W.,2025-09-02,6:00 pm,7:00 pm,,,ETUTORING,,2025-08-31 3:32:27 pm,"Whiteford, Hannah",,,
42,Graduate Writing FA25,Hannah W.,2025-09-02,7:00 pm,8:00 pm,,,ETUTORING,,2025-08-31 3:32:34 pm,"Whiteford, Hannah",,,
43,Graduate Writing FA25,Hannah W.,2025-09-02,8:00 pm,9:00 pm,,,ETUTORING,,2025-08-31 3:32:58 pm,"Whiteford, Hannah",,,
44,Graduate Writing FA25,Hannah N.,2025-09-02,6:00 pm,7:00 pm,,,ETUTORING,,2025-09-01 1:17:20 pm,"Morey, Allyson",,,
45,Graduate Writing FA25,Hannah N.,2025-09-02,7:00 pm,8:00 pm,,,ETUTORING,,2025-09-01 1:17:30 pm,"Morey, Allyson",,,
46,Writing Center/Humanities Tutoring FA25,Morgan M.,2025-09-02,4:30 pm,8:00 pm,,,,,2025-09-02 9:32:29 am,"Borro, Nicole",,,
47,STEM Center,Quoc N.,2025-09-02,6:00 pm,7:00 pm,,YES,ONLINE,MATH115 Applied Math for Business - Mr Patrick...,2025-08-30 8:02:29 am,"Clarke, amanda",,,dr. patrick chadowski

======================================================================
⭐ STEM CENTER FILTERED RESULTS ⭐
======================================================================
Found 34 STEM Center entries out of 48 total

,Schedule Title,Staff or Resource,Appointment Date,Start Time,End Time,Walk-In/Drop-In,Missed/No-Show,Online,Focus,Created,Created By,Repeating,Course,Course instructor
0,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,2:00 pm,2:30 pm,,,,,2025-08-27 9:15:22 am,"Clay, Carter",,,Dr. Prier
1,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,3:00 pm,3:30 pm,,,,,2025-08-27 9:16:23 am,"Clay, Carter",,,Dr. Prier
2,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,2:30 pm,3:00 pm,,,,,2025-08-27 9:17:18 am,"Clay, Carter",,,Dr. Prier
3,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,3:30 pm,4:00 pm,,,,,2025-08-27 9:18:02 am,"Clay, Carter",,,Dr. Prier
4,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,4:00 pm,4:30 pm,,,,,2025-08-27 9:18:55 am,"Clay, Carter",,,Dr. Prier
5,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,4:30 pm,5:00 pm,,,,,2025-08-27 9:20:32 am,"Clay, Carter",,,Dr. Prier
6,STEM Center,Lexa Y.,2025-09-02,2:00 pm,3:00 pm,,,0,CHEM105 Physiological Chem - Dr Aaron Forbes,2025-08-28 6:26:49 pm,"Dunn, Chloe",,,Dr. Aaron Forbes
7,STEM Center,Quoc N.,2025-09-02,5:00 pm,6:00 pm,,,0,BCOR111 Prin Microecomonics - Dr M Roth,2025-08-28 7:28:03 pm,"Tejwani, Drishti",,,Roth
11,STEM Center,Kara B.,2025-09-02,2:00 pm,3:00 pm,,,0,CHEM103 Chemistry of Life 1 - Dr Betty Jo Chit...,2025-08-29 9:48:00 am,"Liberati, Nick",,,Chitester
12,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,5:00 pm,5:30 pm,,,,,2025-08-29 10:02:28 am,"Sebastian, Nora",,,Michael Caulfield
13,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,6:30 pm,7:00 pm,,,,,2025-08-29 11:19:11 am,"Gankhuyag, Altangerel",,,Michael Caulfield
14,STEM Center,Matthew T.,2025-09-02,7:00 pm,8:00 pm,,,0,CHEM114 General Chemistry 2 - any instructors,2025-08-29 11:24:14 am,"Bikeet, Carol Amir Boshra Abdo",,,Dr.Tallmadge
17,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,5:30 pm,6:00 pm,,,,,2025-08-31 5:56:34 pm,"Orte Blanch, Claudia",,,Dr. Prier
18,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,6:00 pm,6:30 pm,,,,,2025-08-31 5:57:09 pm,"Orte Blanch, Claudia",,,Dr. Prier
20,STEM Center,Matthew T.,2025-09-02,5:00 pm,6:00 pm,,,ONLINE,SPRT391 Physio Exrc Sprt Lab - Ms Kara Kern,2025-09-01 6:22:32 pm,"Cernuto, Olivia",,,Dr. Kara Kern
21,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,6:00 pm,6:30 pm,,,,,2025-09-01 7:38:41 pm,"Garrido Lecca Zagaceta, Bastiaan",,,David Prier
22,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,7:30 pm,8:00 pm,,,,,2025-09-01 7:39:32 pm,"Garrido Lecca Zagaceta, Bastiaan",,,David Prier
24,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,5:00 pm,5:30 pm,,,,,2025-09-02 12:04:04 am,"Wasielewski, Maja",,,Dr. Prier
25,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,3:00 pm,3:30 pm,,,,,2025-09-02 6:32:39 am,"Dhakal, Sambriddhi",,,David Prier
26,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,3:30 pm,4:00 pm,,,,,2025-09-02 6:33:15 am,"Dhakal, Sambriddhi",,,David Prier
27,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,2:30 pm,3:00 pm,,,,,2025-09-02 6:34:05 am,"Dhakal, Sambriddhi",,,David Prier
29,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,5:00 pm,5:30 pm,,,,,2025-09-02 8:43:45 am,"Wright, Erin",,,Michael J Caulfield
30,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,5:30 pm,6:00 pm,,,,,2025-09-02 8:46:57 am,"Wright, Erin",,,Michael J Caulfield
31,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,6:00 pm,6:30 pm,,,,,2025-09-02 8:54:26 am,"Wright, Erin",,,Michael J Caulfield
32,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,2:00 pm,2:30 pm,,,,,2025-09-02 9:13:13 am,"Le, Tue",,,Michael Caufield
33,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,7:00 pm,7:30 pm,,,,,2025-09-02 9:17:45 am,"Vizcaino, Tommi",,,David Prier
34,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,4:30 pm,5:00 pm,,,,,2025-09-02 9:33:01 am,"Norman, Sadie",,,Prier
35,STEM Center,Cloe M.,2025-09-02,2:00 pm,3:00 pm,,,0,ME201 Statics - any instructors,2025-09-02 10:06:09 am,"Mateo Villaronga, Cloe",,,steinbrink
36,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,7:30 pm,8:00 pm,,,,,2025-09-02 12:58:12 pm,"Baktybekov, Tamirlan",,,Michael Caulfield
37,STEM Center,Clara B.,2025-09-02,4:00 pm,5:00 pm,YES,,0,MATH140 Calculus 1 - any instructors,2025-09-02 3:01:29 pm,"Bourke Hurtado, Clara",,,Dr. Prier
38,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,6:30 pm,7:00 pm,,,,,2025-09-02 3:36:14 pm,"Baktybekov, Tamirlan",,,Michael Caulfield
39,STEM Center Proctored Exams,Calculus Readiness Exam,2025-09-02,7:00 pm,7:30 pm,,,,,2025-09-02 3:41:57 pm,"Baktybekov, Tamirlan",,,Michael Caulfield
40,STEM Center,Khanh L.,2025-09-02,7:00 pm,8:00 pm,,,0,BIOL115 Hum Anatomy Phys 1 - Mrs Renee Foradori,2025-09-02 4:31:03 pm,"Tran, Nguyen Thuc",,,foradori
47,STEM Center,Quoc N.,2025-09-02,6:00 pm,7:00 pm,,YES,ONLINE,MATH115 Applied Math for Business - Mr Patrick...,2025-08-30 8:02:29 am,"Clarke, amanda",,,dr. patrick chadowski